EmployeeRazorPagesApp/Pages/EmployeeDetails/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EmployeeRazorPagesApp.Models;
using EmployeeRazorPagesApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EmployeeRazorPagesApp.Pages.EmployeeDetails
{
    public class DetailsModel : PageModel
    {

        private readonly IEmployeeRepo _Emprepo;

        public Employee EmpPropertydeatils { get; set; }

        public DetailsModel(IEmployeeRepo employeeRepo)
        {
            this._Emprepo = employeeRepo;
        }
        public IActionResult OnGet(int ID)
        {
            EmpPropertydeatils = _Emprepo.GetEmployeebyID(ID);

            if(EmpPropertydeatils  == null)
            {
                return  RedirectToPage ("/Notound");

            }
            return Page();
        }
    }
}

EmployeeRazorPagesApp/Pages/EmployeeDetails/EditEmp.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EmployeeRazorPagesApp.Models;
using EmployeeRazorPagesApp.Services;

namespace RazorEmployeeDetailsMyProj.Pages.Employees
{
    public class EditEmpModel : PageModel
    {
        private readonly IEmployeeRepo employeeRepositoryint;
        private readonly IWebHostEnvironment webHostEnvironment;

        public EditEmpModel(IEmployeeRepo employeeRepositoryint, IWebHostEnvironment webHostEnvironment)
        {
            this.employeeRepositoryint = employeeRepositoryint;
            this.webHostEnvironment = webHostEnvironment;
        }
        [BindProperty]
        public Employee Employee { get;  set; }

        [BindProperty]
        public IFormFile Photo { get; set; }

        [BindProperty]
        public bool Notify { get; set; }

        public string Message { get; set; }


        public IActionResult OnGet(int? id)
        {
            if (id.HasValue)
            {
                Employee = employeeRepositoryint.GetEmployeebyID(id.Value);
            }
            else
            {
                Employee = new Employee();


            }

            if (Employee == null)
            {
                return RedirectToPage("/NotFound");
            }

            return Page();
        }

        public IActionResult OnPost()
        {

            if (ModelState.IsValid)
            {

                if (Photo != null)
                {
                    // If a new photo is uploaded, the existing photo must be
                    // deleted. So check if there is an existing photo and delete
                    if (Employee.Photopath != null)
                    {
                        string filePath = Path.Combine(webHostEnvironment.WebRootPath,
                            "images", Employee.Photopath);
                        System.IO.File.Delete(filePath);
                    }
                    // Save the new photo in wwwroot/images folder and update
                    // PhotoPath property of the employee object
                    Employee.Photopath = ProcessUploadedFile();
                }

                if (Employee.ID > 0)
                { 
                Employee = employeeRepositoryint.Update(Employee);
                }

                else
                {
                    Employee = employeeRepositoryint.Add(Employee);


                }
                return RedirectToPage("Index");

            }
            return Page();

        }

        private string ProcessUploadedFile()
        {
            string uniqueFileName = null;

            if (Photo != null)
            {
                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Photo.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    Photo.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }

        public void OnPostUpdateNotificationPreferences(int id)
        {
            if (Notify)
            {
                Message = "Thank you for turning on notifications";
            }
            else
            {
                Message = "You have turned off email notifications";
            }

            Employee = employeeRepositoryint.GetEmployeebyID(id);
        }

    }
}

EmployeeRazorPagesApp/Pages/EmployeeDetails/EditTry.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EmployeeRazorPagesApp.Models;
using EmployeeRazorPagesApp.Services;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace EmployeeRazorPagesApp.Pages.EmployeeDetails
{
    public class EditTryModel : PageModel
    {
        private readonly IEmployeeRepo iemployeeRepo;
        private readonly IWebHostEnvironment webHostEnvironment;

        [BindProperty]
        public Employee EmpEditProperty { get; set; }

        [BindProperty]
        public IFormFile Photo { get; set; }
        public EditTryModel(IEmployeeRepo iemployeeRepo, IWebHostEnvironment webHostEnvironment)
        {
            this.iemployeeRepo = iemployeeRepo;
            this.webHostEnvironment = webHostEnvironment;
        }
        public IActionResult OnGet(int ID)
        {
            EmpEditProperty = iemployeeRepo.GetEmployeebyID(ID);

            if(EmpEditProperty==null)
            {
                return RedirectToPage("/NotFound");

            }

            return Page();
        }

        public IActionResult OnPost(Employee employee)
        {
            if (Photo != null)
            {
                // If a new photo is uploaded, the existing photo must be
                // deleted. So check if there is an existing photo and delete
                if (employee.Photopath != null)
                {
                    string filePath = Path.Combine(webHostEnvironment.WebRootPath,
                        "images", employee.Photopath);
                    System.IO.File.Delete(filePath);
                }
                // Save the new photo in wwwroot/images folder and update
                // PhotoPath property of the employee object
                employee.Photopath = ProcessUploadedFile();
            }

            Employee Emp=  iemployeeRepo.Update(employee);
            return RedirectToPage("Index");

        }

        private string ProcessUploadedFile()
        {
            string uniqueFileName = null;

            if (Photo != null)
            {
                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Photo.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    Photo.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }
    }
}

EmployeeRazorPagesApp/Pages/EmployeeDetails/Edit_2.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EmployeeRazorPagesApp.Models;
using EmployeeRazorPagesApp.Services;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;

namespace EmployeeRazorPagesApp.Pages
{
    public class Edit_2Model : PageModel
    {
        private readonly IEmployeeRepo iemployeeRepo;
        [BindProperty]
        public Employee empeditprop { get; set; }

        [BindProperty]
        public IFormFile Photo { get; set; }
        public IWebHostEnvironment WebHostEnvironment { get; set; }

        public Edit_2Model(IEmployeeRepo _IemployeeRepo, IWebHostEnvironment webHostEnvironment)
        {
            this.iemployeeRepo = _IemployeeRepo;
           this.WebHostEnvironment = webHostEnvironment;
            
        }
        public IActionResult OnGet(int id)
        {

            empeditprop = iemployeeRepo.GetEmployeebyID(id);

            if(empeditprop==null)
            {
                return RedirectToPage("Index");
            }

            return Page();

        }

        public IActionResult OnPost(Employee employee)
        {
            if (Photo != null)
            {
                // If a new photo is uploaded, the existing photo must be
                // deleted. So check if there is an existing photo and delete
                if (employee.Photopath != null)
                {
                    string filePath = Path.Combine(WebHostEnvironment.WebRootPath,
                        "images", employee.Photopath);
                    System.IO.File.Delete(filePath);
                }
                // Save the new photo in wwwroot/images folder and update
                // PhotoPath property of the employee object
                employee.Photopath = ProcessUploadedFile();
            }

            Employee Emp = iemployeeRepo.Update(employee);
            return RedirectToPage("Index");

        }

        private string ProcessUploadedFile()
        {
            string uniqueFileName = null;

            if (Photo != null)
            {
                string uploadsFolder = Path.Combine(WebHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Photo.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    Photo.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }
    }
}

EmployeeRazorPagesApp/Pages/EmployeeDetails/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EmployeeRazorPagesApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EmployeeRazorPagesApp.Models;

namespace EmployeeRazorPagesApp.Pages.EmployeeDetails
{
    public class IndexModel : PageModel
    {
        private readonly IEmployeeRepo _employeeRepo;

        public IEnumerable<Employee> EmpProperty { get; set; }
        public IndexModel(IEmployeeRepo employeeRepo)
        {
          this._employeeRepo = employeeRepo;
        }
        public void OnGet()
        {
            EmpProperty = _employeeRepo.GetEmployees();
        }
    }
}

EmployeeRazorPagesApp/Pages/EmployeeDetails/Details.cshtml
@page "/Employees/View/{id}"
@model EmployeeRazorPagesApp.Pages.EmployeeDetails.DetailsModel
@{

    ViewData["Title"] = "Details";
    var photopath = "~/Images/" + (Model.EmpPropertydeatils.Photopath ?? "default.jpg");
}
<style>

    .btn{

        width:80px;
    }

</style>

<div class="row justify-content-center m-3">
    <div class="col-sm-8">
        <div class="card">
            <div class="card-header">
                <h1>@Model.EmpPropertydeatils.Name</h1>
            </div>

            <div class="card-body text-center">
                <img class="card-img-top" src="@photopath" asp-append-version="true"/>
                <h4>Employee_ID : @Model.EmpPropertydeatils.ID</h4>
                <h4>Email:        @Model.EmpPropertydeatils.Email</h4>
                <h4>Department:   @Model.EmpPropertydeatils.Department</h4>

            </div>

            <div class="card-footer text-center">
                <a asp-page="Index" class="btn btn-primary">Back</a>
                <a href="#" class="btn btn-primary">EDIT</a>
                <a href="#" class="btn btn-danger">DELETE</a>

            </div>

        </div>
    </div>
</div>

EmployeeRazorPagesApp/Pages/EmployeeDetails/EditEmp.cshtml
@page "{id:min(1)?}/{handler?}"
@model RazorEmployeeDetailsMyProj.Pages.Employees.EditEmpModel
@{

    var photoPath = "~/images/" + (Model.Employee.Photopath ?? "noimage.jpg");

    var pageHeader = Model.Employee.ID > 0 ? "Edit" : "Create";

}


<h1>Notification Preferences</h1>

<form method="post" asp-page-handler="UpdateNotificationPreferences">
    <div class="form-check">
        <input asp-for="Notify" class="form-check-input" />
        <label asp-for="Notify" class="form-check-label">
            Receive email notification when my details change
        </label>
    </div>
    <button type="submit" class="btn btn-primary">
        Update Notification Preferences
    </button>
    @if (!string.IsNullOrEmpty(Model.Message))
    {
        <div class="alert alert-primary">
            @Model.Message
        </div>
    }

</form>

<hr />

<br />
<hr />







<h1>Edit employee </h1>

<h1>@pageHeader</h1>


<form method="post" class="mt-3" enctype="multipart/form-data" asp-page-handler="OnPost">

    <input hidden asp-for="Employee.ID" />

    <input hidden asp-for="Employee.Photopath" />



    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group row">
        <label asp-for="Employee.Name" class="col-sm-2 col-form-label">
        </label>
        <div class="col-sm-10">
            <input asp-for="Employee.Name" class="form-control" placeholder="Name">
            <span asp-validation-for="Employee.Name" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Employee.Email" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Employee.Email" class="form-control" placeholder="Email">
            <span asp-validation-for="Employee.Email" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="Employee.Department" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <select asp-for="Employee.Department" class="custom-select mr-sm-2"
                    asp-items="Html.GetEnumSelectList<Dept>()">
                <option value="">Please Select</option>
            </select>
            <span asp-validation-for="Employee.Department" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="Photo" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <div class="custom-file">
                
                <input asp-for="Photo" class="custom-file-input form-control">
                <label class="custom-file-label">Click here to change photo</label>
            </div>
        </div>
    </div>

    <div class="form-group row col-sm-4 offset-4">
        <img class="imageThumbnail" src="@photoPath" asp-append-version="true" />
    </div>

    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">SAVEUpdateEmp</button>
            <a asp-page="/Employees/Index" class="btn btn-primary">Cancel</a>
        </div>
    </div>

   
    @section Scripts {
        <script>
            $(document).ready(function () {
                $('.custom-file-input').on("change", function () {
                    var fileName = $(this).val().split("\\").pop();
                    $(this).next('.custom-file-label').html(fileName);
                });
            });
        </script>

        <partial name="_ValidationScriptsPartial" />
    }

</form>

EmployeeRazorPagesApp/Pages/EmployeeDetails/EditTry.cshtml
@page
@model EmployeeRazorPagesApp.Pages.EmployeeDetails.EditTryModel
@{
    var photoPath = "~/Images/" + (Model.EmpEditProperty.Photopath ?? "default.jpg");

}

<form method="post" class="mt-3" enctype="multipart/form-data">
    @*Use hidden input elements to store employee id which
        we need when we submit the form*@
    <input hidden asp-for="EmpEditProperty.ID" />
    <input hidden asp-for="EmpEditProperty.Photopath" />

    @*asp-for tag helper takes care of displaying the existing
        data in the respective input elements*@
    <div class="form-group row">
        <label asp-for="EmpEditProperty.Name" class="col-sm-2 col-form-label">
        </label>
        <div class="col-sm-10">
            <input asp-for="EmpEditProperty.Name" class="form-control" placeholder="Name">
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="EmpEditProperty.Email" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="EmpEditProperty.Email" class="form-control" placeholder="Email">
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="EmpEditProperty.Department" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <select asp-for="EmpEditProperty.Department" class="custom-select mr-sm-2"
                    asp-items="Html.GetEnumSelectList<Dept>()">
                <option value="">Please Select</option>
            </select>
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="Photo" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <div class="custom-file">
                @*Photo property type is IFormFile, so ASP.NET Core
                    automatically creates a FileUpload control  *@
                <input asp-for="Photo" class="custom-file-input form-control">
                <label class="custom-file-label">Click here to change photo</label>
            </div>
        </div>
    </div>

    <div class="form-group row col-sm-4 offset-4">
        <img class="imagethumbnail" src="@photoPath" asp-append-version="true" />
    </div>

    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Update</button>
            <a asp-page="/EmployeeDetails/Index" class="btn btn-primary">Cancel</a>
        </div>
    </div>


    @section Scripts {
        <script>
            $(document).ready(function () {
                $('.custom-file-input').on("change", function () {
                    var fileName = $(this).val().split("\\").pop();
                    $(this).next('.custom-file-label').html(fileName);
                });
            });
        </script>

        <partial name="_ValidationScriptsPartial" />
    }


</form>

EmployeeRazorPagesApp/Pages/EmployeeDetails/Edit_2.cshtml
@page
@model EmployeeRazorPagesApp.Pages.Edit_2Model
@{
    var photopathvarimg = "~/Images" + (Model.empeditprop.Photopath) ?? ("default.jpg");
}

<!--<form method="post" asp-page-handler="UpdateNotificationPreferences">
    <div class="form-check">
        <input asp-for="Notify" class="form-check-input" />
        <label asp-for="Notify" class="form-check-label">
            Receive email notification when my details change
        </label>
    </div>
    <button type="submit" style="width:auto" class="btn btn-primary">
        Update Notification Preferences
    </button>-->
    @*@if (!string.IsNullOrEmpty(Model.Message))
        {
            <div class="alert alert-primary">
                @Model.Message
            </div>
        }*@

<!--</form>-->

<hr />

<h1>Edit Emp</h1>
<h1>Edit employee </h1>

<form method="post" class="mt-3" enctype="multipart/form-data" asp-page-handler="OnPost">
    @*Use hidden input elements to store employee id which
        we need when we submit the form*@
    <input hidden asp-for="empeditprop.ID" />
    <input hidden asp-for="empeditprop.Photopath" />

    @*asp-for tag helper takes care of displaying the existing
        data in the respective input elements*@
    <div class="form-group row">
        <label asp-for="empeditprop.Name" class="col-sm-2 col-form-label">
        </label>
        <div class="col-sm-10">
            <input asp-for="empeditprop.Name" class="form-control" placeholder="Name">
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="empeditprop.Email" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="empeditprop.Email" class="form-control" placeholder="Email">
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="empeditprop.Department" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <select asp-for="empeditprop.Department" class="custom-select mr-sm-2"
                    asp-items="Html.GetEnumSelectList<Dept>()">
                <option value="">Please Select</option>
            </select>
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="Photo" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <div class="custom-file">
                <input asp-for="Photo" class="custom-file-input form-control" />
                <label class="custom-file-label">Click Here To Change Photo </label>

            </div>
        </div>
    </div>

    <div class="col-sm-4 offset-4">
        <img class="img-thumbnail imageThumbnailstrsuper" src="@photopathvarimg" asp-append-version="true" />

    </div>


    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Update</button>
            <a asp-page="/EmployeeDetails/Index" class="btn btn-primary">Cancel</a>
        </div>
    </div>

    @section Scripts {
        <script>
            $(document).ready(function () {

                $('.custom-file-input').on("change", function () {
                    var filename = $(this).val().split("\\").pop();
                    $(this).next('.custom-file-label').html(filename);
                });
            });

        </script>
    }
</form>

EmployeeRazorPagesApp/Pages/EmployeeDetails/Index.cshtml
@page

@model EmployeeRazorPagesApp.Pages.EmployeeDetails.IndexModel
@{


}

@*<h4>@Model.EmpProperty.Count()</h4>*@

<style>
    .btn{
       width:85px;
    }
</style>

<div class="card-deck">
    @foreach(var employee in Model.EmpProperty)
    {
        var photopath = "~/Images/" + (employee.Photopath ?? "default.jpg");

        <div class="card m-3" style="min-width:18rem; max-width:30.5%;">
            <div class="card-header">
                <h3>@employee.Name</h3>
            </div>
            <img class="card-img-top imagethumbnail" src="@photopath"
                 asp-append-version="true" />
            <div class="card-footer text-center">
                @*<a href="#" class="btn btn-primary m-1">View</a>*@

                <a asp-page="/EmployeeDetails/Details" asp-route-ID="@employee.ID"
                   class="btn btn-primary m-1">View</a>

                <a asp-page="/EmployeeDetails/EditEmp" asp-route-ID="@employee.ID"
                   class="btn btn-primary m-1">EditEmp</a>


                <a asp-page="/EmployeeDetails/EditTry" asp-route-ID="@employee.ID"
                   class="btn btn-primary m-1">EditTry</a>


                <a asp-page="/EmployeeDetails/Edit_2" asp-route-ID="@employee.ID"
                   class="btn btn-primary m-1">Edit_2</a>

            </div>
        </div>

    }

</div>